"""
app/dependencies.py
===================
Shared FastAPI dependency functions.

These are injected into route handlers via FastAPI's Depends() mechanism.

Current dependencies:
  - verify_session_token: validates the Bearer token issued after OTP
    verification and extracts company/email claims from it.

Sprint 2+ additions:
  - get_current_verification_request: validates ownership of a request
    against the session before database operations.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import time

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from app.config import Settings, get_settings

logger = logging.getLogger(__name__)

# FastAPI security scheme for Bearer tokens
_bearer_scheme = HTTPBearer(auto_error=False)

# Session token validity window: 4 hours
_SESSION_TTL_SECONDS = 4 * 60 * 60


def verify_session_token(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer_scheme),
    settings: Settings = Depends(get_settings),
) -> dict:
    """
    Validate the session token issued after OTP verification.

    Returns a dict with:
        company_name: str
        hr_email:     str
        issued_at:    int  (Unix timestamp)

    Raises:
        HTTP 401 if no token, invalid signature, or expired session.

    IMPLEMENTATION NOTE:
        This validates the HMAC-signed token generated by
        email_service._issue_session_token().
        The token format is: base64(payload).HMAC-SHA256(payload)
        where payload = "company_name|hr_email|timestamp"

        This is intentionally simple for Sprint 1.  Before production,
        evaluate whether a proper JWT or server-side session (stored in
        PostgreSQL/Redis) is more appropriate.
    """
    if not credentials or not credentials.credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "success": False,
                "message": "Email verification required. Please verify your HR email first.",
                "error_code": "EMAIL_VERIFICATION_REQUIRED",
            },
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = credentials.credentials
    try:
        encoded_payload, provided_sig = token.rsplit(".", 1)
        payload_bytes = base64.urlsafe_b64decode(encoded_payload + "==")
        payload = payload_bytes.decode()
        company_name, hr_email, ts_str = payload.split("|", 2)
        issued_at = int(ts_str)
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "success": False,
                "message": "Invalid session token. Please re-verify your email.",
                "error_code": "INVALID_SESSION_TOKEN",
            },
        )

    # Verify signature
    expected_sig = hmac.new(
        settings.APP_SECRET_KEY.encode(),
        payload.encode(),
        hashlib.sha256,
    ).hexdigest()

    if not hmac.compare_digest(expected_sig, provided_sig):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "success": False,
                "message": "Session token signature is invalid.",
                "error_code": "INVALID_SESSION_SIGNATURE",
            },
        )

    # Check expiry
    if time.time() - issued_at > _SESSION_TTL_SECONDS:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "success": False,
                "message": "Your session has expired. Please re-verify your email.",
                "error_code": "SESSION_EXPIRED",
            },
        )

    return {
        "company_name": company_name,
        "hr_email": hr_email,
        "issued_at": issued_at,
    }
